### ISSUE TITLE
Empty inventory

### ISSUE THREAD

**Issue by alexanderkoller** [minecraft-saar/infrastructure#13]
After I connect, I don't have a block in my hand, so I can't place a block. Should it be like this?

<img width="966" alt="Screenshot 2020-03-25 at 09 11 55" src="https://user-images.githubusercontent.com/8291392/77515415-ccd71500-6e78-11ea-8448-130ac93e3310.png">

**Comment by akoehn** [comment]
You have to press e and drag a block into your inventory.
null

**Comment by alexanderkoller** [comment]
This will confuse a lot of players. Why can't we add blocks to the player's hand with these methods?

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/HumanEntity.html#setItemInHand-org.bukkit.inventory.ItemStack-

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/Inventory.html#addItem-org.bukkit.inventory.ItemStack...-

**Comment by ca-schaefer** [comment]
On the developer branch of the Plugin, there is already a draft for adding blocks to the player's inventory. It isn't on the master yet because we haven't decided which blocks should be there (https://github.com/minecraft-saar/spigot-plugin/issues/16)

**Comment by akoehn** [comment]
Ah, now it is also in master ...

I lost track of what was already implemented in the developer branch, can we either develop on master directly or push to master sooner?  We try to mark stable versions with tags, so not every commit on master needs to be perfect.

**Comment by akoehn** [comment]
And it is now also deployed on the live server.

**Comment by alexanderkoller** [comment]
Hm. My hand and inventory are still empty. Is there anything I can try on my end?

<img width="966" alt="Screenshot 2020-03-25 at 12 47 48" src="https://user-images.githubusercontent.com/8291392/77533304-e8511880-6e96-11ea-8ba7-e9520287862d.png">

**Comment by akoehn** [comment]
I have no clue, it works for me.

**Comment by akoehn** [comment]
Seems to work for everyone with the latest commits.
