### ISSUE TITLE
Clearer game start process

### ISSUE THREAD

**Issue by alexanderkoller** [minecraft-saar/infrastructure#14]
Currently after joining a game on minecraft.coli, the player is temporarily placed in a celestial void (see screenshot). It takes a few seconds to load the game world and put the player into a place that is recognizable as a Minecraft world.

Can we figure out a way to either put the player into a more realistic-looking environment immediately or at least show a message that says "Initializing, please wait ..." or some such?

<img width="966" alt="Screenshot 2020-03-25 at 12 47 25" src="https://user-images.githubusercontent.com/8291392/77533436-25b5a600-6e97-11ea-8ffd-dea155ae5e99.png">

**Comment by akoehn** [comment]
We now show messages upon joining.  These could be tweaked a bit (I will do that today) and maybe @ca-schaefer could make sure that it is always daytime in the starting world?

**Comment by alexanderkoller** [comment]
Can this be closed?

**Comment by akoehn** [comment]
Yes, especially since players are now teleportet nearly instantaneous to their world.
